version: '3.8'
services:
  konteiner-2:
    build: 
      context: ./backend
      dockerfile: ./Dockerfile
    image: konteiner-2
    container_name: konteiner-2
    ports:
      - "8180:80"
    volumes: 
      - /opt/Dikt_webapp/database/Diktdatabase.db:/usr/local/apache2/cgi-bin/Diktdatabase.db
    restart: always
    networks:
      konteiner-nettverk:
        ipv4_address: 172.20.0.2
    
    # capabilites begrensninger
    cap_drop:
      - ALL
    cap_add:
      - SETUID
      - SETGID
      - NET_BIND_SERVICE
    
    # cgroup begrensninger 
    cpuset: "1"
    cpu_shares: 512
    cpu_percent: 40
    pids_limit: 100


  konteiner-3:
    build: 
      context: ./frontend
      dockerfile: ./Dockerfile
    image: konteiner-3
    container_name: konteiner-3
    ports:
      - "8080:80"
    restart: always
    networks:
      konteiner-nettverk:
        ipv4_address: 172.20.0.3
    
    # capabilites begrensninger
    cap_drop:
      - ALL
    cap_add:
      - SETUID
      - SETGID
      - NET_BIND_SERVICE
    
    # cgroup begrensninger 
    cpuset: "1"
    cpu_shares: 512
    cpu_percent: 40
    pids_limit: 100

# Konteiner-nettverk
networks:
  konteiner-nettverk:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: "172.20.0.0/16"
          gateway: "172.20.0.1"
