version: '3'
services:
  dikt-image: 
    build: 
      context: .
      dockerfile: Dockerfile
    image: dikt-image

  konteiner-2:
    build: 
      context: ./backend
      dockerfile: ./Dockerfile
    image: konteiner-2
    container_name: konteiner-2
    ports:
      - "8180:80"
    volumes: 
      - /opt/Dikt_webapp/database/Diktdatabase.db:/usr/local/apache2/cgi-bin/Diktdatabase.db
    restart: always
    depends_on:
      - dikt-image

  konteiner-3:
    build: 
      context: ./frontend
      dockerfile: ./Dockerfile
    image: konteiner-3
    container_name: konteiner-3
    ports:
      - "8080:80"
    restart: always
    depends_on:
      - dikt-image
